apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podBlockName }}
  labels:
    name: ol7slim-test
spec:
  restartPolicy: Always
  containers:
    - image: container-registry.oracle.com/os/oraclelinux:7-slim
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      name: ol7slim
      volumeDevices:
        - name: vol
          devicePath: /dev/block
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: {{ .Values.pvcBlockName }}
