apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvExistingFilesystemName }}
  annotations:
    pv.kubernetes.io/provisioned-by: zfssa-csi-driver
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.volSize }}
  csi:
    driver: zfssa-csi-driver
    volumeHandle: /nfs/{{ .Values.applianceName }}/{{ .Values.pvExistingFilesystemName }}/{{ .Values.appliance.pool }}/local/{{ .Values.appliance.project }}/{{ .Values.pvExistingFilesystemName }}
    readOnly: false
    volumeAttributes:
      nfsServer: {{ .Values.appliance.nfsServer }}
      share: {{ .Values.volMountPoint }}
      rootGroup: {{ .Values.appliance.rootGroup }}
      rootPermissions: "777"
      rootUser: {{ .Values.appliance.rootUser }}

  claimRef:
    namespace: default
    name: {{ .Values.pvcExistingFilesystemName }}

