apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcExistingFilesystemName }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volSize }}
  storageClassName: {{ .Values.scExistingFilesystemName }}
