apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvExistingName }}
  annotations:
    pv.kubernetes.io/provisioned-by: zfssa-csi-driver
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.volSize }}
  csi:
    driver: zfssa-csi-driver
    volumeHandle: /iscsi/{{ .Values.applianceName }}/{{ .Values.pvExistingName }}/{{ .Values.appliance.pool }}/local/{{ .Values.appliance.project }}/{{ .Values.pvExistingName }}
    readOnly: false
    volumeAttributes:
      targetGroup: {{ .Values.appliance.targetGroup }}
      targetPortal: {{ .Values.appliance.targetPortal }}
  claimRef:
    namespace: default
    name: {{ .Values.pvcExistingName }}

